### ISSUE TITLE
Still needed to manually npm install lots of packages

### ISSUE THREAD

**Issue by erezsh** [svelte-add/mdsvex#8]
I followed the instructions, but got messages like 

```
Cannot find module 'rehype-autolink-headings'
```

I had to npm install lots of packages, like `rehype-autolink-headings`, `rehype-slug`, `remark-abbr`, and `remark-github`.

Maybe I missed something or did it wrong, I'm a noob at js packaging, but just thought you should know.

Btw loved the demo page. As a megalomaniac it really spoke to me.

**Comment by babichjacob** [comment]
I'm really surprised, because the only way those packages get referenced is if examples are included, and if examples are included then those packages are added to the dependency list. And if they're in the dependency list, an `npm install` (with no arguments) will install them, just like it installs `mdsvex` which it sounds like you didn't have to manually install?

Can you see if it happens a second time (i.e. in a new project)?

**Comment by erezsh** [comment]
Turns out I missed that I had to run `npm install` after.

Apologies for my noobiness.

**Comment by babichjacob** [comment]
> Btw loved the demo page. As a megalomaniac it really spoke to me.

I forgot to comment on this that, believe me, I understand. There's a reason it's the default to include examples like this!
